version: '2'
services:
  web:
    build: .
    ports:
    - "8443:8443"
    links:
    - mysql
    - mongo
    env_file:
    - docker.env
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    image: mysql
  mongo:
    image: mongo
    ports:
    - "27018:27017"